### ISSUE TITLE
labelHaplotypes with unambiguously assigned haplotypes

### ISSUE THREAD

**Issue by KerensaMcElroy** [EricArcher/strataG#13]
The code for renaming ambiguous haplotypes as NA appears to be breaking the code for generating gtypes. I'm getting the following error when running labelHaplotypes(my.gtype):

Error in .local(.Object, ...) : 
  the following haplotypes can't be found in sequences for locus 'haps': NA
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
2: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
3: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
4: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
5: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
6: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state

**Comment by EricArcher** [comment]
Would you attach an .rdata file with your `my.gtype` object so I can see what it looks like? Also, have you installed the latest version of strataG from GitHub?

**Comment by KerensaMcElroy** [comment]
Please find .rdata file attached. I installed strataG today, via install.packages('strataG'). sessionInfo() gives strataG_1.0.5. 
[gtype.rdata.zip](https://github.com/EricArcher/strataG/files/809705/gtype.rdata.zip)

**Comment by EricArcher** [comment]
Thanks! I'll take a look at this, but would you install the latest version from GitHub:

```
# make sure you have Rtools installed
if (!require('devtools')) install.packages('devtools')
# install from GitHub
devtools::install_github('ericarcher/strataG', build_vignettes = TRUE)
```

**Comment by KerensaMcElroy** [comment]
Hi Eric,

I did what you suggested and installed from source. It did fix the lableHaplotypes() problem, however now I have another problem. When I use new() to make a gytpes object and specify the strata, I get 
'Warning message:
In .local(.Object, ...) :
  the length of 'strata' is not the same as the number of individuals. strata will be recycled.'

Previously, this code worked fine. Also, on loading the library, I have:

Error in FUN(X[[i]], ...) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/strataG/data/Rdata.rdb' is corrupt
In addition: Warning messages:
1: In FUN(X[[i]], ...) : restarting interrupted promise evaluation
2: In FUN(X[[i]], ...) : internal error -3 in R_decompress1

Unsurprisingly given this, I can no longer run the test data either. Furthermore, the help for function new() is no longer available.

Thanks again,

Kerensa.

**Comment by EricArcher** [comment]
Hmmm... Would you do a full un-install of strataG (`remove.packages("strataG")`) and then reinstall from GitHub? I've seen that corruption error before on other packages when new versions do not properly overwrite everything on installation.

This should solve access to the help files. Instead of using `new` to create your gtypes object though, you might want to look at `df2gtypes` which is a bit more convenient for most applications.

Let me know if you run into more issues.

**Comment by KerensaMcElroy** [comment]
Hi again,

I've been playing around a bit with this again. Is there a way of using df2gtypes, if your only genetic data is sequence data as a DNAbin object? 

Thanks,

Kerensa.

**Comment by EricArcher** [comment]
see `sequence2gtypes` which should do what you want.
