### ISSUE TITLE
Registering Routines

### ISSUE THREAD

**Issue by zkamvar** [EricArcher/strataG#15]
I noticed your comment on an Rcpp thread a while ago about Registering Routines and saw this post recently. I thought it might help when R 3.4 is released: https://ironholds.org/registering-routines/

**Comment by EricArcher** [comment]
Correct. Thanks, I saw that too, and have been waiting for 3.4 for that reason before I went through the process and (re-)submitting the latest version to CRAN. 
I know I could build R-devel and get it that way, but my system is federally managed (yay!) and building it has some hassles I'd rather avoid.

**Comment by zkamvar** [comment]
Luckily, you don't need to build R-devel to do it. Since it's just written in R, it can be simply sourced: https://gist.github.com/Ironholds/b93b589b17c3315f766d3e2988533558

```r
devtools::source_gist("b93b589b17c3315f766d3e2988533558", filename = "routines.R")
package_native_routine_registration_skeleton(dir = ".")
```

It worked for me: https://github.com/grunwaldlab/poppr/issues/124 😄

**Comment by EricArcher** [comment]
Cool! I totally should have thought of that! Thanks!

**Comment by EricArcher** [comment]
Obviously, I didn't read the article, just mentally filed it away for when 3.4 comes out. I really need to slow down and take things in...

**Comment by zkamvar** [comment]
Yeah, but it can be hard when you're being pulled at from 3 million different directions. It's a good philosophy on life, though!
