### ISSUE TITLE
Problems to run FastSimCoal with strataG r

### ISSUE THREAD

**Issue by juan1610** [EricArcher/strataG#18]
Dear Eric 
I have some issues to run FastSimCoal with strataG r 
I am following the scripts to simulate http://onlinelibrary.wiley.com/store/10.1111/1755-0998.12559/asset/supinfo/men12559-sup-0001-AppendixS1.R?v=1&s=de6dcdaf0c2c298d4ba925ea282432429d203d80

Although I have setting the Path to 
setwd("C:/Users/JuanM/Desktop/SIMULATION IN ECOLOGY AN GENETIC/FASTSIMCOAL/fsc_win64")
But wen I tried to run an error appears in the R console I'm using Rstudio and R 3.4.1 and Windows 10

Error in fastsimcoal(pop.info, msat.params, mig.rates, hist.ev) : 
  fastsimcoal exited with error 1
In addition: Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c fsc252 -i fsc.run.par -n 1 -q -S  ' had status 1 
2: In shell(cmd.line, intern = F) :
  'fsc252 -i fsc.run.par -n 1 -q -S  ' execution failed with error code 1
> sim.sub <- lapply(c(50, 100, 500), function(x) {
+   ran.loc <- sample(locNames(sim.msats), x)
+   sim.msats[, ran.loc, ] 

Any advice because I'm interested to use FastSimCoal with strataG r
Thanks in advance 
Have a good day
Dr. Juan Manuel Penaloza Ramirez
Secretaría de Desarrollo Institucional
Torre de Rectoría 8° piso, Ciudad Universitaria, UNAM

**Comment by EricArcher** [comment]
This appears to be an error generated by fastsimcoal and not R or strataG. To help diagnose, in the fastsimcoal function, add the argument `delete.files = FALSE` and re-run.
Then in the folder that has the file `fsc.run.par`, on the command line, run
`fsc252 -i fsc.run.par -n 1 -q -S`
and examine the error that is returned.
