### ISSUE TITLE
Calculation of critical M 

### ISSUE THREAD

**Issue by mastoffel** [EricArcher/strataG#2]
It would be really useful to calculate the critical M  through simulation as decribed in Garza and Williamson (2001), for comparison with the empirical M-ratio.

**Comment by EricArcher** [comment]
The simulation will have to be case-specific so there is no way to easily automate it in `mRatio()`. However, strataG has a powerful wrapper for fastsimcoal2 that can be easily used to construct a simulation to obtain p-values from. See `?strataG::fscWrite()`, `?strataG::fscRun()`, and `fscTutorial()`.
