### ISSUE TITLE
Can't use ldNe on windows

### ISSUE THREAD

**Issue by annabarbanti** [EricArcher/strataG#27]
Hi Eric, 

I am trying to use the ldNe function in R v 3.6.0, but when I run the code: 

**>ne <- ldNe(gty, maf.threshold = 0, by.strata = FALSE, ci = 0.95)**

I get this error:

**Error in mclapply(1:ncol(loc.pairs), compLoc, loc.pairs = loc.pairs, mat = mat,  : 
  'mc.cores' > 1 is not supported on Windows**

Is there a way to solve this? Is it a problem of my R version that maybe I can solve? 

Thank you very much!
Anna

**Comment by EricArcher** [comment]
Are you using the version of strataG from CRAN? If so, would you install the devel version from GitHub? I've done a lot of bug fixes and modifications. This error shouldn't happen in this version.

**Comment by annabarbanti** [comment]
Yes I was. I tried to install it from GitHub but it gives me this error:

**Error: Failed to install 'strataG' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘Hmisc’**

which is a package I haven't installed, or at least not actively. I tried to remove the package but the program says it doesn't exist in my library.

**Comment by EricArcher** [comment]
Hmmm.  I'm not sure what you mean by "not actively". The error implies that you have a previous version of Hmisc installed and the strataG installation.
Can you tell me the version number of strataG that you currently have installed?

**Comment by annabarbanti** [comment]
Ok yes I saw now that Hmisc is a dependency of strataG
the current version of strataG I have installed is "strataG_2.0.2" from CRAN

**Comment by annabarbanti** [comment]
Looks like deleting the Hmisc before deleting the CRAN version of strataG worked! And looks like the function is working.

Thank you!

**Comment by EricArcher** [comment]
Glad to hear it.
