### ISSUE TITLE
Enhancement request: convert genlight to gtypes

### ISSUE THREAD

**Issue by lkomoro** [EricArcher/strataG#28]
It would be great if there was a function to convert genlight to gtypes to faciliate integration of agedenet and strataG with larger SNP datasets.

**Comment by thierrygosselin** [comment]
in the meantime, you can use [radiator::genomic_converter ](https://thierrygosselin.github.io/radiator/reference/genomic_converter.html)function:

```
test <- radiator::genomic_converter(data = your.genlight.object, output = "gtypes")
# test is a list with a tidy dataset and your new gtypes object...
```

to give it a try: [radiator installation instructions](https://thierrygosselin.github.io/radiator/index.html#installation)

**Comment by EricArcher** [comment]
added genlight2gtypes and gtypes2genlight conversion functions
