### ISSUE TITLE
readGenData doesn't exclude NA's

### ISSUE THREAD

**Issue by PAMorin** [EricArcher/strataG#35]
readGenData with na.strings = c(NA, "NA", "", " ", "?", ".") incorporates "NA" as an allele, not missing data.

**Comment by EricArcher** [comment]
There seems to be an issue with the `na.strings` argument in `data.table::fread()` not recognizing `"NA"` in some circumstances. I've bypassed that in an edit to`readGenData()` so that all strings in `na.strings` will be converted to `NA` after the data is read in.
