### ISSUE TITLE
arlequinRead() doesn't read my samples 

### ISSUE THREAD

**Issue by valebernald** [EricArcher/strataG#39]
Hi Eric!

I didn't saw this issue, so I want to ask you about a problem that I have executing the function arlequinRead. 

I have an arlequin file (.arp) of SNPs data. When I execute the function arlequinRead I have no error in the console. Nevertheless, when I check the file that was created (list), the "data.info" shows a "list of length 0". This is how it looks:
<img width="696" alt="Captura de Pantalla 2020-08-04 a la(s) 15 41 36" src="https://user-images.githubusercontent.com/60018977/89337553-188c9d00-d669-11ea-8147-c71e1c5c5c3f.png">

I've tried with different arlequin files that I have, but it always show me the same. Then I can't go on with the arp2gtype to continue with the analyses. I don't know if there is a problem with mi data, I don't understand why the function doesn't read my samples. This is a picture of the structure of my data: 
<img width="1280" alt="Captura de Pantalla 2020-08-04 a la(s) 15 40 08" src="https://user-images.githubusercontent.com/60018977/89337355-d19ea780-d668-11ea-803b-f46ae61bb606.png">

I'm using v2.4.905 of strataG

Cheers,
Valentina

**Comment by EricArcher** [comment]
Would you email me (eric.archer@noaa.gov) a copy of your .arp file and I'll see if I can figure out what is happening.

**Comment by valebernald** [comment]
Hi Eric!

I would like to know if you had time to check the file I sent you?

Cheers,
Valentina

**Comment by EricArcher** [comment]
I have, but I am having a problem recompiling the package to test fixes. There is an issue in something that has changed in a recent version of either R, Rcpp, or MacOS Catalina that causes a crash with compiled C code in the package. I'm working on it this week as I have time and will post when I have a fix. Sorry for the delay.

**Comment by valebernald** [comment]
Thanks Eric!

**Comment by EricArcher** [comment]
Apologies for the delay on this. I've fixed the bugs responsible for this and it seems to read your .arp file properly now.
