### ISSUE TITLE
Enhancement request: extra-parameters ALPHA and UNIFPRIORALPHA as arguments

### ISSUE THREAD

**Issue by fernandabiologia** [EricArcher/strataG#42]
Hi Eric,

Thanks for creating STRATAG. I was wondering if it would be possible to make the extraparameters ALPHA and UNIFPRIORALPHA to be arguments that can be defined by the user. In that way one could follow the suggestions in Wang 2017 ("The computer program STRUCTURE for assigning individuals to populations: easy to use but easier to misuse") and try the alternative ancestry prior and different values of ALPHA when analysing unbalanced samples. 

Cheers,

Fernanda.

**Comment by EricArcher** [comment]
Thanks for the suggestion. This should be do-able. You've caught me at a good time. I'm starting some bug fixing and restructuring of bits of the code. Due to some personal leave I'm taking and other work, I expect the package to be updated on CRAN by the end of October.
Sorry for any delays that causes.

**Comment by fernandabiologia** [comment]
Hi Eric,

Thank you for your reply. I'm glad you'll have some time to look into it. For the moment I managed to alter the function so I could change those parameters, but it will be great to have them as arguments in the updated version. Looking forward to it.

**Comment by EricArcher** [comment]
I've added the following parameters to `structureWrite()`:   inferalpha, alpha, unifprioralpha, alphamax, alphapriora, alphapriorb. Would you let me know if they are working for you.

**Comment by fernandabiologia** [comment]
Hi Eric,

I just tested with my data and it's working perfectly. Thanks for updating it.
