### ISSUE TITLE
Parameter estimation using fastsimcoal - using non-SNP data

### ISSUE THREAD

**Issue by mariaemilyd** [EricArcher/strataG#44]
Hi Eric,

Me again! Not really an issue but more of a question.

Does the strataG interface for fastsimcoal allow for parameter estimation using genetic data other than SNPS (e..g microsats/STRs)?

I noticed if I try and specify parameters using fscSettingsEst() it won't work if you don't specify an obs.sfs?

Error in fscSettingsEst(fscEstParam("NCUR", is.int = TRUE, distr = "unif",  : 
  object 'obs.sfs' not found

**Comment by EricArcher** [comment]
In short, the answer is no. I'm not familiar with using fastsimcoal to do parameter estimation with data other than SFS. If you can point me to guidance of how this is done, I will look into incorporating it into the strataG interface.

**Comment by mariaemilyd** [comment]
Thanks Eric, I'm looking into it. I have found this example on the fsc google group where someone asked for help: https://groups.google.com/g/fastsimcoal/c/VkaQa-ZYMBo/m/rJ7CNWnBAgAJ but no other material yet.
