### ISSUE TITLE
Issues with downloading StrataG on R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"

### ISSUE THREAD

**Issue by jbkoch** [EricArcher/strataG#45]
Dear Dr. Archer,

I am having issues with downloading strataG on the most recent version of R (R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"). What version of R should I use to use strataG? Thank you very much! Below is the error message.

I do look forward to using this package for my work!

aloha,
Jon

> install.packages("strataG")
Warning in install.packages :
  package ‘strataG’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by EricArcher** [comment]
Sorry for the problems you're having. I'm trying to put an update together to send to CRAN but just don't have the focused time I'd like to be able to do it quickly. There are also several issues I'm working through changes in Rcpp integration and Mac OS X Catalina that are taking some time.
Are you able to install from GitHub?

**Comment by jbkoch** [comment]
Wow! Thanks for fast reply. I'm actually trying the GitHub approach now...and it seems like these are going smoothly. Sorry to bother on the issue with install.packages(). Thanks for developing such a great resource.

**Comment by jbkoch** [comment]
FYI - I had some issues with installing via GitHub. 

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/mapdata_2.3.0.tgz'
Content type 'application/x-gzip' length 25465976 bytes (24.3 MB)
===========================================
downloaded 20.9 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  (converted from warning) downloaded length 21953836 != reported length 25465976
Error: Failed to install 'strataG' from GitHub:
  (converted from warning) download of package ‘mapdata’ failed

So I downloaded 'mapdata' (v2.3.0) independently prior to the 'strataG' download...then the download worked fine.

**Comment by EricArcher** [comment]
Thanks for the update. I'll leave this issue open as a reminder to check the `mapdata` dependencies when I do a re-release.

**Comment by Cotissima** [comment]
Hi!
I have been trying to download strataG to R version 4.1.0 from Linux Ubuntu. I had a similar issue when trying the GitHub installation. However, my problem is that Copula is not installed but went attempting to install, it fails because gsl is needed. When trying to install gsl, I get the following error "configure: error: Need GSL version >= 1.16", but  I have the latest GSL version installed on my machine.  Do you have any suggestions on how to overcome this problem? I would be eternally grateful. Thank you!!
Cota

**Comment by EricArcher** [comment]
I don't think this is the same problem as the one in this issue. `strataG` does not have a dependency on GSL directly. It does require `copula`, so if you are getting this error on the `copula` install, I would suggest checking with the maintainers of that package. Sorry I can't be of more help on this error.
