### ISSUE TITLE
Issues with compiling from GitHub

### ISSUE THREAD

**Issue by BartPannebakker** [EricArcher/strataG#48]
Hi Eric,

With the CRAN library not available, I am trying to compile from GitHub, but I get stuck in the final stages of the compilation of strataG on MacOs 11.2. It returns the following error:

clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o strataG.so RcppExports.o calc_FstStats.o calc_Phist.o misc_funcs.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [strataG.so] Error 1
   ERROR: compilation failed for package ‘strataG’
─  removing ‘/private/var/folders/87/q5h9lnyj30161gjy8bq5pwk80000gn/T/RtmpEvbY2v/Rinst97783d66c54b/strataG’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'strataG' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o strataG.so RcppExports.o calc_FstStats.o calc_Phist.o misc_funcs.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
E> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
E> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
E> ld: library not found for -lgfortran
E> clang: error: linker command failed with 

Hope you can point me in the right direction,

Thanks in advance, Bart

**Comment by EricArcher** [comment]
This seems to be an issue with your compiler configuration on your Mac. [Here](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) is one resource that may help.

**Comment by BartPannebakker** [comment]
Thanks for your quick reply Eric, I will give it a try later tonight!
Regards, Bart
