### ISSUE TITLE
Dependency {rmetasim} no longer available for R-4.0.4

### ISSUE THREAD

**Issue by ericacasun** [EricArcher/strataG#49]
Hi Dr. Archer, 

I was trying to install {strataG}, and I've also tried installing it from GitHub but it was still unsuccessful. It seems like one of the dependencies, {rmetasim}, was removed from CRAN. I was wondering if there are any fixes? Thank you for helping!

Kind regards,
Erica

**Comment by EricArcher** [comment]
Install it from Allan Strand's GitHub repository with:

`devtools::install_github("stranda/rmetasim")`
