### ISSUE TITLE
labelHaplotypes 

### ISSUE THREAD

**Issue by juance100** [EricArcher/strataG#5]
After applying the function labelHaplotipes the functions to estimate diverse parameters such as nucleotide diversity o haplotype diversity return an error message:
Example
> secprueba <- sequence2gtypes(prueba, strata)
> secpruebaL <- labelHaplotypes(secprueba)
> ndgL <- nucleotideDivergence(secpruebaL)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘ploidy’ for signature ‘"list"’

The problem is solved using:
> ndgL <- nucleotideDivergence(secpruebaL$gtypes)

Cheers

**Comment by EricArcher** [comment]
Correct.  This is as it should be. For a gtypes object, labelHaplotypes returns a list that contains an element with the new gtypes object (gtypes) and an element for any unassigned haplotypes (unassigned). See the details in ?labelHaplotypes.

I should make a test at the beginning of all functions taking gtypes objects to test that they are of the correct class and return a more informative error if they are not. I will put it on my to-do list.
