### ISSUE TITLE
Can't install strataG in R version 4.2.0

### ISSUE THREAD

**Issue by GabrielaPinho** [EricArcher/strataG#56]
Dear Dr. Archer,

I have been trying to install strataG unsuccessfully and I hope you can help me. When I use install.packages('strataG') I get "package ‘strataG’ is not available for this version of R", and when I try though github I receive the message: "Error: Failed to install 'strataG' from GitHub:
  Failed to install 'rmetasim' from GitHub:
  ! System command 'R' failed"

Sorry to bother and thank you.

**Comment by EricArcher** [comment]
You'll have to install rmetasim directly from its GitHub repository:

devtools::install_github("stranda/rmetasim")

Then install strataG from GitHub

**Comment by GabrielaPinho** [comment]
Thank you very much. I worked perfectly!

**Comment by EricArcher** [comment]
Glad to hear it!
