### ISSUE TITLE
Issue with installation on Mac?

### ISSUE THREAD

**Issue by jbkoch** [EricArcher/strataG#59]
Dear Dr. Archer,

I have used strataG before and found it to very helpful in my research. I have returned to the use the package again and I am running into a problem I haven't encountered before in the installation:

> library(devtools)
Loading required package: usethis
> devtools::install_github('ericarcher/strataG', build_vignettes = TRUE)
Downloading GitHub repo ericarcher/strataG@HEAD

 **ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [strataG.so] Error 1
   ERROR: compilation failed for package ‘strataG’
─  removing ‘/private/var/folders/d7/20yz1mrj5l37c6j98ykn3sth0000gn/T/RtmpHEFrPv/Rinstfc3633506f/strataG’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'strataG' from GitHub:
  ! System command 'R' failed**

OS: MacOS Monterey Version 12.6
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"

Thank you for your time!

**Comment by EricArcher** [comment]
Hi Jonathan,

This error looks is a Fortran configuration issue on your machine, not something to do with strataG. Check /Library/Frameworks/R.framework/Resources/etc/Makeconf to make sure that the compilers are all pointing to the right places for your system.

Cheers,
Eric
