### ISSUE TITLE
Error in structureRun

### ISSUE THREAD

**Issue by shankarkshakya** [EricArcher/strataG#6]
I wasn't able to perform STRUCTURE with function structureRun. Keep getting the following error. 

> structureRun(msats.g, k = 2:5, num.k.rep = 1)
Error in structureRead(files["out"], sw.out$pops) : 
  the file 'dolphin.msats.structureRun/dolphin.msats.structureRun.k2.r1_out_f' can't be found.

**Comment by EricArcher** [comment]
For documentation and help troubleshooting, please provide as much information as possible about your system and the conditions of the error (e.g., where STRUCTURE is installed, does STRUCTURE run, does that folder and file actually exist, etc).

**Comment by shankarkshakya** [comment]
Solution to my previous posted problem.

I updated my path so that R knows where to find STRUCTURE. Thanks to Zhian Kamvar.

Sys.setenv(PATH = paste("C:\\Users\\Kaji\\Desktop\\Structure2.3.4\\bin", Sys.getenv("PATH"), sep = ";"))
