### ISSUE TITLE
Problems running fastsimcoal2 with strataG in R

### ISSUE THREAD

**Issue by talimc** [EricArcher/strataG#62]
Hi Eric,

Thank you so much for creating the access to run fastsimcoal2 in R using strataG. I've been following your fscTutorial, following Bernd Gruber's function in dartR (gl.sfs). However, I wasn't able to run your tutorial because of this error:

ex1.params <- fscRun(ex1.params, num.sim = 1)
2023-07-01 21:21:16 running fastsimcoal2...
Error in fscRun(ex1.params, num.sim = 1) : 
  2023-07-01 21:21:16 fastsimcoal exited with error 127. The command was:
fsc26 --ifile ex1.par --numsims 1 --allsites  --quiet

This error seems to occur with every simulated data that I've tried (including Bernd Gruber's from here: https://groups.google.com/g/dartr/c/2SzqUIhkwPw). 

My fsc version is fsc27_win64, and is located in my working directory. 

I'd really appreciate your help with this. 

Thank you,

Tali

**Comment by EricArcher** [comment]
The error is because as you say, your executable for fastsimcoal is not 'fsc26', which is the default. Supply the actual executable name to the `exec` argument in `fscRun()`. See `?fscRun`

**Comment by talimc** [comment]
Thank you for the quick response - but I just tried it:
system.time(est.p <- fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc2709"
+ ))
2023-07-02 12:18:03 running fastsimcoal2...
Error in fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc2709") : 
  2023-07-02 12:18:03 fastsimcoal exited with error 127. The command was:
fsc2709 --tplfile est.habdestroy.tpl --numsims 20 -e est.habdestroy.est --dnatosnp 0 --msfs --jobs --allsites --maxlhood --numloops 20 --minnumloops 20 --brentol 0.01 --cores 8 --numBatches 8 --quiet
Timing stopped at: 0 0 0

or:

system.time(est.p <- fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc27"
+ ))
2023-07-02 12:18:16 running fastsimcoal2...
Error in fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc27") : 
  2023-07-02 12:18:16 fastsimcoal exited with error 127. The command was:
fsc27 --tplfile est.habdestroy.tpl --numsims 20 -e est.habdestroy.est --dnatosnp 0 --msfs --jobs --allsites --maxlhood --numloops 20 --minnumloops 20 --brentol 0.01 --cores 8 --numBatches 8 --quiet
Timing stopped at: 0 0 0

And still get the same error; 

could it be anything else?

Thank you,

Tali

**Comment by EricArcher** [comment]
The requirement is that the fastsimcoal executable is in the PATH, such that you can run it from any folder. Confirm this by opening a terminal window and typing the name of the executable and pressing ENTER/RETURN. You should see a list of command line options for the executable. Whatever the executable command you enter on the command line is the value that `exec` should get.

**Comment by talimc** [comment]
Hi Eric,
I did run it in the terminal window:

C:\Users\windows\Desktop\Myna_comparative_genomics>fsc2709
fsc was launched without any argument: attempting to read file "fsc_run.txt"
Unable to find file "fsc_run.txt" in current directory(C:\Users\windows\Desktop\Myna_comparative_genomics)


fastSimcoal2 (ver 2.7.0.9 - 11.04.22)

Usage:

 -h  --help              : prints this help
 -i  --ifile test.par    : name of parameter file
 -n  --numsims 1000      : number of simulations to perform
                           Also applies for parameter estimation
 -t  --tplfile test.tpl  : name of template parameter file (optional)
 -f  --dfile test.def    : name of parameter definition file (optional)
 -F  --dFile test.def    : same as -f, but only uses simple parameters defined
                           in template file. Complex params are recomputed
 -e  --estfile test.est  : parameter prior definition file (optional)
                           Parameters drawn from specified distributions are
                           substituted into template file.
 -E  --numest 10         : number of draws from parameter priors (optional)
                           Listed parameter values are substituted in template file
 -g  --genotypic         : generates arlequin projects with genotypic data
 -p  --phased            : specifies that phase is known in arlequin output
                           default: phase is unknown
 -s  --dnatosnp 2000     : output DNA as SNP data, and specify maximum no. of SNPs
                           to output (use 0 to output all SNPs).
 -S  --allsites          : output the whole DNA sequence, incl. monomorphic sites
 -I  --inf               : generates DNA mutations according to an
                           infinite site (IS) mutation model
 -d  --dsfs              : computes derived site frequency spectrum
                           (for SNP or DNA as SNP (-s) data only).
 -m  --msfs              : computes minor site frequency spectrum
                           (for SNP or DNA as SNP (-s) data only)
 -j  --jobs              : output one simulated or bootstrapped SFS per file
                           in a separate directory for easier analysis
                           (requires -d or -m and -s0 options)
 -b  --numboot 10        : number of bootstraps to perform on polymorphic sites to extract SFS
                           (should be used in addition to -s0 and -j options)
 -H  --header            : generates header in site frequency spectrum files
 -q  --quiet             : minimal message output to console
 -T  --tree              : outputs coalescent tree in nexus format
 -k  --keep  10000       : number of simulated polymorphic sites kept in memory
                           If the simulated no. is larger, then temporary files
                           are created. Default value is 10000
 -r  --seed              : seed for random number generator (positive integer <= 1E6)
 -x  --noarloutput       : does not generate Arlequin output
 -G  --indgenot          : generates an individual genotype table
 -M  --maxlhood          : perform parameter estimation by max lhood from SFS
                           values between iterations
 -L  --numloops 20       : number of loops (ECM cycles) to perform during
                           lhood maximization. Default is 20
 -l  --minnumloops 2     : number of  loops (ECM cycles) for which the lhood is
                           computed on both monomorphic and polymorphic sites
                           if REFERENCE parameter is defined
 -C  --minSFSCount 1     : minimum observed SFS entry count taken into account in
                           likelihood computation (default = 1, but value can be < 1. e.g  0.5)
 -0  --removeZeroSFS     : do not take into account monomorphic sites for SFS
                           likelihood computation
 -a  --ascDeme 0         : This is the deme id where ascertainment is performed
                           when simulating SNPs. Default: no ascertainment.
 -A  --ascSize 2         : number of ascertained chromosomes used to define SNPs in
                           a given deme. Optional parameter. Default value is 2
 -u   --multiSFS         : generate or use multidimensional SFS
 -w   --brentol 0.01     : tolerance for Brent optimization
                           Default = 0.01. Smaller value imply more precise estimations
                           but require more computation time (min;max) = (1e-1;1e-5)
 -c   --cores 1          : number of openMP threads for parameter estimation
                           (default=1, max=numBatches, use 0 to let openMP choose optimal value)
 -B   --numBatches 12    : max. no. of batches for multi-threaded runs
                           (default=12)
 -P   --pooledsfs        : computes pooled SFS over all samples.
                           Assumes -d or -m, but not -u flag activated
      --recordMRCA       : records tMRCAs for each non recombining segment and outputs
                           results in <generic name>_mrca.txt. Beware: huge slow down of computing time
      --foldedSFS        : computes the 1D and 2D MAF SFS by simply folding the DAF SFS
      --logprecision 23  : precision for computation of logs of random numbers. Max value is 23
                           Default value is 23 (full precision). Recommended lower value is 18
      --initValues my.pv : specifies a file (*.pv) containing initial parameter values
                           for parameter optimization
      --nosingleton      : ignores singletons in likelihood computation

However, I still get the same error when running the fsctrun command with this version:

system.time(est.p <- fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc2709"))
2023-07-02 21:16:37 running fastsimcoal2...
Error in fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc2709") : 
  2023-07-02 21:16:37 fastsimcoal exited with error 127. The command was:
fsc2709 --tplfile est.habdestroy.tpl --numsims 20 -e est.habdestroy.est --dnatosnp 0 --msfs --jobs --allsites --maxlhood --numloops 20 --minnumloops 20 --brentol 0.01 --cores 8 --numBatches 8 --quiet
Timing stopped at: 0.03 0.02 0.04

I must be doing something wrong?

**Comment by EricArcher** [comment]
Error code 127 indicates that the command can't be found. 
Can you execute `fsc2709` from other directories to confirm that it is in your PATH?

**Comment by talimc** [comment]
If I move the entire fsc27_win64 folder to the desktop and execute fsc2709 it runs fine (gives the list of command line options), but when I setwd to there and run fsc_run from here, it gives the same error as before.

**Comment by talimc** [comment]
I just managed to run it (until it failed for a different reason)  from the command line (terminal) window using this code:

fsc2709 --tplfile est.habdestroy.tpl --numsims 20 -e est.habdestroy.est --dnatosnp 0 --msfs --jobs --allsites --maxlhood --numloops 20 --minnumloops 20 --brentol 0.01  --quiet

This is the output:
fastsimcoal was invoked with the following command line arguments:
fsc2709 --tplfile est.habdestroy.tpl --numsims 20 -e est.habdestroy.est --dnatosnp 0 --msfs --jobs --allsites --maxlhood --numloops 20 --minnumloops 20 --brentol 0.01 --quiet

WARNING: The [RULES] section is not supported (or read) since version 2.7.
         All rules defined in this section will be ignored


Random generator seed : 170939

No population growth detected in input file

Estimating model parameters using 12 batches and 1 thread

Observed data file ("../est.habdestroy_jointMAFpop0_0.obs") does not seem to be present
Unable to compute the likelihood
TSimSettings::performBrenMinimization: Unable to read observed SFS and to estimate parameters ...

Program total execution time: 0.571 seconds

But I still can't run it in the Console.

And the follow up question would be - why is my obs file read like a jointMAF and not an MAF? 
(I realize this is a question for dartR but maybe you've had experience with this as well)
I am using the 'gl.sfs' function in dartR:
obs.p<-gl.sfs(gl,singlepop = T)
#followed by opening it in Notepad++ to rearrange it. 

Thank you,

Tali

**Comment by EricArcher** [comment]
Can you confirm that your PATH has been edited to include the folder that fsc2709 is in?

If so, confirm that you can run `fsc2709` from any folder by opening a terminal window and going to a folder that `fsc2709` is **not** in and executing `fsc2709` by itself.

If that works, then from within R (also making sure that the working directory is **not** the same as one that contains `fsc2709`), run `system2("fsc2709")`. You _should_ see the same output as when you executed it on the command line.

If this works, then `fscRun()` should work under the same conditions, because `fscRun()` executes `system2("fsc2709")` plus the command line options as the error report shows. (assuming that the `exec` argument is set to `fsc2709`).

**Comment by talimc** [comment]
I confirmed that:
the PATH includes the folder that fsc2709 is in;
I can run fsc2709 from any folder;
I can run system2("fsc2709") in R;

BUT
I get this error when I try to run this code:

system.time(est.p <- fscRun(est.p, num.sims = 20, num.cores = 10, exec = "fsc2709", sfs.type = "maf", dna.to.snp = T, quiet = F))

2023-07-05 18:29:55 running fastsimcoal2...
Error in setwd(p$folder) : cannot change working directory
In addition: Warning message:
'dna.to.snp' set to 'FALSE' because 'fscBlock_dna()' or 'fscBlock_snp()' not used. 
Timing stopped at: 0 0 0

Hopefully it's a small last tweak?

**Comment by EricArcher** [comment]
I would need to see your call to `fscWrite()` that creates `est.p`. 
If the `use.wd` argument to that is FALSE, then it is trying to write to a folder created by the R command `tempdir()`. It is assumed that you have permissions to create that folder and make it the current working directory.
If `use.wd` is TRUE, then it is using your current working directory, so I don't see how that error would arise.

**Comment by talimc** [comment]
It solved it!
use.wd was set to default (FALSE), so I changed it into use.wd=T. 

Thank you!

**Comment by EricArcher** [comment]
Great. Just for the record, can you tell me what you get if you issue the following to the R prompt?

```
x <- tempdir()
setwd(x)
```

**Comment by talimc** [comment]
Of course:

> x <- tempdir()
> setwd(x)
> x
[1] "C:\\Users\\windows\\AppData\\Local\\Temp\\Rtmpy2YLbU"

**Comment by EricArcher** [comment]
That's odd. The last error you reported before is based on this code in essence. 
Would you try one more line to confirm that your system _actually_ changed the working directory to the temporary folder and you don't get the same error as before? I want to see if there is something I should be trapping in my code as this hasn't been reported before.

```
x <- tempdir()
setwd(x)
getwd()
```

**Comment by talimc** [comment]
It's not generating the same error again - I have no idea why; I can run it now with the default setting in 'fscWrite':

> est.p2 <- fscRun(est.p, num.sims = 1000, num.cores = 10, exec = "fsc2709", sfs.type = "maf", quiet = F)
2023-07-06 11:55:03 running fastsimcoal2...
2023-07-06 11:55:11 run complete

> system.time(est.p2 <- fscRun(est.p, num.sims = 1000, num.cores = 10, exec = "fsc2709", sfs.type = "maf", quiet = F))
2023-07-06 11:55:12 running fastsimcoal2...
2023-07-06 11:55:19 run complete
   user  system elapsed 
   0.01    0.03    7.93

**Comment by EricArcher** [comment]
Phew. Must have been some bad bits in your system. Glad to know its all working now.
