### ISSUE TITLE
Wrong Structure of write.arlequin()

### ISSUE THREAD

**Issue by xiekunwhy** [EricArcher/strataG#9]
Hi,
When I use write.arlequin() to write out of my data, I found that the structure of output file was wrong.
[[Structure]]
StructureName="A group of 6 populations analyzed for DNA"
NbGroups=1
Group= {
"1"
"2"
"3"
"4"
"5"
"6"
}
Much different from arlequin example data:
	[[Structure]]
		StructureName="An example of structure with 5 geographic regions"
		NbGroups=5
		#Asia
		Group={
		"Oriental" 
		"Tharu"
		}
		#Africa
		Group={
			"Wolof"
			"Peul"
		}
		#America
		Group={
			"Pima"
			"Maya"
		}
		#Europe
		Group={
			"Finnish"
			"Sicilian"
		}
		#Middle East
		Group={
			"Israeli Jew"
			"Israeli Arab"
		}

Actually I have six group and each group has different sample sizes. The strata of my gtypes object like follows:
strata(gt)
aa ab ac ad ae af ag ah ai aj ak al am an ao ap aq ar as at au av aw ax ay az ba bb bc bd be bf bg bh bi bj bk bl bm bn bo bp bq br bs bt bu bv bw bx by bz ca cb cc cd ce cf cg ch ci cj ck cl cm 
 6  6  6  6  3  3  3  3  3  3  3  3  1  1  1  1  3  3  5  5  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  5  5  5  1  1  5  5  6  6  6  6  6  6  4  6  1  1 
cn co cp cq cr cs ct cu cv cw cx cy cz da db dc dd de df dg dh di dj dk dl dm dn do dp dq dr ds dt du dv dw dx dy dz ea eb ec ed ee ef eg eh ei ej ek el em en eo ep eq er es et eu ev ew ex ey ez 
 6  3  6  6  6  6  4  1  6  6  6  6  4  5  5  6  6  5  6  6  6  6  6  6  5  6  3  5  5  4  4  4  5  5  5  5  4  4  4  4  6  6  4  4  4  6  5  5  4  5  1  6  6  4  5  4  1  1  5  1  5  1  1  1  1 
fa fb fc fd fe ff fg fh fi fj fk fl fm fn fo fp fq fr fs ft fu fv fw fx fy fz ga gb gc gd ge gf gg gh gi gj gk gl gm gn go gp gq gr gs gt gu gv gw gx gy gz ha hb hc hd he hf hg hh hi hj hk hl hm 
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  2  3  6  6  6  6  6  6  6  5  5  5  5  5  5  5  5  5  1  1  1  1  1  4  6  6  3  6  6  6  6  6  6  6  6  6  6  6  6 
hn ho hp hq hr hs ht hu hv hw hx hy hz ia ib ic id ie if ig ih ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js jt ju jv jw jx jy jz 
 6  1  1  2  5  6  3  3  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  6  3  3  6  6  6  6  4  3  6  6  6  5  6  6  6  1  1  1  6  6  6  6  6  6  6  6  6  6 
ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf lg lh li lj lk ll lm ln 
 6  4  2  5  6  6  6  6  6  5  6  6  6  4  1  5  6  6  6  6  6  6  6  6  6  6  6  6  6  6  1  3  6  6  6  6  6  6  6  6 
Levels: 1 2 3 4 5 6
So, is there some thing wrong with write.arlequin() function?

Best wishes!

**Comment by EricArcher** [comment]
This is not an error in the write.arlequin() function. The input file structure from the Arlequin example is based on a hierarchical analysis. In that example, there are 5 groups, each of which has 2 populations in it. Currently, strataG does not support hierarchical analyses like this, so it is designed to simply write Arlequin input files that have 1 group with the number of populations (strata) specified in the gtypes object. In your case, this is 6. You should be able to read this file in Arlequin and do normal stratified analyses. 
However, if you have a hierarchical design you can easily edit the [[Structure]] section by hand to indicate these groupings of strata as in the example.

Cheers,
Eric
